<?php exit(0); ?> { 
"settings":
{
	"data_settings" : 
	{
		"save_database" : 
		{
			"database" : "auau2012_veta",
			"is_present" : true,
			"password" : "Proz@c01",
			"port" : 3306,
			"server" : "localhost",
			"tablename" : "newsletter-registry-form",
			"username" : "auau2012_admindb"
		},
		"save_file" : 
		{
			"filename" : "VETA-Newsletter-registry-form-results.csv",
			"is_present" : true
		},
		"save_sqlite" : 
		{
			"database" : "newsletter-registry-form.dat",
			"is_present" : false,
			"tablename" : "newsletter-registry-form"
		}
	},
	"email_settings" : 
	{
		"auto_response_message" : 
		{
			"custom" : 
			{
				"body" : "<!DOCTYPE html>\n<html dir=\"ltr\" lang=\"en\">\n<head><title>You got mail!</title></head>\n<body style=\"background-color: #f9f9f9; padding-left: 11%; padding-top: 7%; padding-right: 2%; max-width: 700px; font-family: Helvetica, Arial;\">\n<style type=\"text/css\">\nbody {background-color: #f9f9f9;padding-left: 110px;padding-top: 70px; padding-right: 20px;max-width:700px;font-family: Helvetica, Arial;}\np{font-size: 12px; color: #666666;}\nh2{font-size: 28px !important;color: #666666 ! important;margin: 0px; border-bottom: 1px dotted #00A2FF; padding-bottom:3px;}\ntable{width:80%;}\ntd {font-size: 12px !important; line-height: 30px;color: #666666 !important; margin: 0px;border-bottom: 1px solid #e9e9e9;}\ntd:first-child {font-size: 13px !important; font-weight:bold; color: #333 !important; vertical-align:text-top; min-width:10%; padding-right:5px;}\na:link {color:#666666; text-decoration:underline;} a:visited {color:#666666; text-decoration:none;} a:hover {color:#00A2FF;}\nb{font-weight: bold;}\n</style>\n<h2 style=\"font-size: 28px !important;color: #666666 ! important;margin: 0px; border-bottom: 1px dotted #00A2FF; padding-bottom:3px;\">Thanks for taking the time to fill out the form. <br/>Here's a copy of what you submitted:</h2>\n<div>\n[_form_results_]\n</div>\n</body>\n</html>\n",
				"is_present" : true,
				"subject" : "Thank you for your submission"
			},
			"from" : "",
			"is_present" : false,
			"to" : ""
		},
		"notification_message" : 
		{
			"bcc" : "",
			"cc" : "admissions@australiaveta.com.au",
			"custom" : 
			{
				"body" : "<!DOCTYPE html>\n<html dir=\"ltr\" lang=\"en\">\n<head><title>You got mail!</title></head>\n<body style=\"background-color: #f9f9f9; padding-left: 11%; padding-top: 7%; padding-right: 20px; max-width: 700px; font-family: Helvetica, Arial;\">\n<style type=\"text/css\">\nbody {background-color: #f9f9f9;padding-left: 11%; padding-top: 7%; padding-right: 2%;max-width:700px;font-family: Helvetica, Arial;}\np{font-size: 12px; color: #666666;}\nh1{font-size: 60px !important;color: #cccccc !important;margin:0px;}\nh2{font-size: 28px !important;color: #666666 ! important;margin: 0px; border-bottom: 1px dotted #00A2FF; padding-bottom:3px;}\ntable{width:80%;}\ntd {font-size: 12px !important; line-height: 30px;color: #666666 !important; margin: 0px;border-bottom: 1px solid #e9e9e9;}\ntd:first-child {font-size: 13px !important; font-weight:bold; color: #333 !important; vertical-align:text-top; min-width:10%; padding-right:5px;}\na:link {color:#666666; text-decoration:underline;} a:visited {color:#666666; text-decoration:none;} a:hover {color:#00A2FF;}\nb{font-weight: bold;}\n</style>\n<h1 style=\"font-size: 60px !important; color: #cccccc !important; margin: 0px;\">Hey there,</h1>\n<p style=\"font-size: 12px; color: #666666;\">\nSomeone filled out your <strong>Newsletter Registry Form</strong> at www.australiaveta.com.au, and here's what they said:\n</p>\n<div>\n[_form_results_]\n<p style=\"font-size: 12px; color: #666666;\">\n<!--\n<b style=\"font-weight: bold;\">Note: </b> Customizing your email message is as easy as 1-2-3! To get started, edit your form and go into the <b style=\"font-weight: bold;\">Settings &gt; Email Notices Tab</b> and then click on <b style=\"font-weight: bold;\">\"Configure email message\"</b>. Web Form Builder supports HTML and CSS so there is no limit to how snazzy you can design your message.\nFor more info <a href=\"http://coffeecup.com\" style=\"color: #666666; text-decoration: underline;\">go here</a>.\nHope you're enjoying the software!\n-->\n</p>\n</div>\n</body>\n</html>",
				"is_present" : true,
				"subject" : "Somebody filled out your form!"
			},
			"from" : "admissions@australiaveta.com.au",
			"is_present" : true,
			"replyto" : "[EMAIL]",
			"to" : "yovannyuseche@australiaveta.com.au"
		}
	},
	"general_settings" : 
	{
		"colorboxautoenabled" : false,
		"colorboxautotime" : 3,
		"colorboxenabled" : false,
		"colorboxname" : "Default",
		"formname" : "VETA-Newsletter-NewForm",
		"is_appstore" : "0",
		"timezone" : "Australia/Sydney"
	},
	"mailchimp" : 
	{
		"apiKey" : "c41f2b6cc30335ea6c22fc4cc6722975-us5",
		"lists" : 
		[
			
			{
				"action" : 
				{
					"subscribe" : 
					{
						"condition" : "always"
					},
					"unsubscribe" : 
					{
						"condition" : "never"
					}
				},
				"is_present" : true,
				"listid" : "0efa012141",
				"merge_tags" : 
				[
					
					{
						"fb_name" : "fname",
						"field_type" : "text",
						"isGrouping" : false,
						"name" : "Nombre / Name",
						"req" : true,
						"tag" : "FNAME"
					},
					
					{
						"fb_name" : "lname",
						"field_type" : "text",
						"isGrouping" : false,
						"name" : "Apellido / Last Name",
						"req" : true,
						"tag" : "LNAME"
					},
					
					{
						"fb_name" : "email",
						"field_type" : "email",
						"isGrouping" : false,
						"name" : "Correo Electrónico / Email Address",
						"req" : true,
						"tag" : "EMAIL"
					},
					
					{
						"dateformat" : "",
						"fb_name" : "dob",
						"field_type" : "date",
						"isGrouping" : false,
						"name" : "Fecha de Nacimiento / DOB",
						"req" : false,
						"tag" : "DOB"
					},
					
					{
						"choices" : 
						[
							":: Tu Pais de origen / Where are you from? ::",
							"Afghanistan",
							"Albania",
							"Algeria",
							"American Samoa",
							"Andorra",
							"Angola",
							"Anguilla",
							"Antarctica",
							"Antigua And Barbuda",
							"Argentina",
							"Armenia",
							"Aruba",
							"Australia",
							"Austria",
							"Azerbaijan",
							"Bahamas",
							"Bahrain",
							"Bangladesh",
							"Barbados",
							"Belarus",
							"Belgium",
							"Belize",
							"Benin",
							"Bermuda",
							"Bhutan",
							"Bolivia",
							"Bosnia and Herzegovina",
							"Botswana",
							"Bouvet Island",
							"Brazil",
							"British Indian Ocean Territory",
							"Brunei Darussalam",
							"Bulgaria",
							"Burkina Faso",
							"Burundi",
							"Cambodia",
							"Cameroon",
							"Canada",
							"Cape Verde",
							"Cayman Islands",
							"Central African Republic",
							"Chad",
							"Chile",
							"China",
							"Christmas Island",
							"Cocos (Keeling) Islands",
							"Colombia",
							"Comoros",
							"Congo",
							"Cook Islands",
							"Costa Rica",
							"Cote D'Ivoire",
							"Croatia",
							"Cuba",
							"Curacao",
							"Cyprus",
							"Czech Republic",
							"Denmark",
							"Djibouti",
							"Dominica",
							"Dominican Republic",
							"East Timor",
							"Ecuador",
							"Egypt",
							"El Salvador",
							"Equatorial Guinea",
							"Eritrea",
							"Estonia",
							"Ethiopia",
							"Falkland Islands",
							"Faroe Islands",
							"Fiji",
							"Finland",
							"France",
							"French Guiana",
							"French Polynesia",
							"French Southern Territories",
							"Gabon",
							"Gambia",
							"Georgia",
							"Germany",
							"Ghana",
							"Gibraltar",
							"Greece",
							"Greenland",
							"Grenada",
							"Guadeloupe",
							"Guam",
							"Guatemala",
							"Guernsey",
							"Guinea",
							"Guinea-Bissau",
							"Guyana",
							"Haiti",
							"Heard and Mc Donald Islands",
							"Honduras",
							"Hong Kong",
							"Hungary",
							"Iceland",
							"India",
							"Indonesia",
							"Iran",
							"Iraq",
							"Ireland",
							"Israel",
							"Italy",
							"Jamaica",
							"Japan",
							"Jersey  (Channel Islands)",
							"Jordan",
							"Kazakhstan",
							"Kenya",
							"Kiribati",
							"Kuwait",
							"Kyrgyzstan",
							"Lao People's Democratic Republic",
							"Latvia",
							"Lebanon",
							"Lesotho",
							"Liberia",
							"Libya",
							"Liechtenstein",
							"Lithuania",
							"Luxembourg",
							"Macau",
							"Macedonia",
							"Madagascar",
							"Malawi",
							"Malaysia",
							"Maldives",
							"Mali",
							"Malta",
							"Marshall Islands",
							"Martinique",
							"Mauritania",
							"Mauritius",
							"Mayotte",
							"Mexico",
							"Micronesia, Federated States of",
							"Moldova, Republic of",
							"Monaco",
							"Mongolia",
							"Montenegro",
							"Montserrat",
							"Morocco",
							"Mozambique",
							"Myanmar",
							"Namibia",
							"Nauru",
							"Nepal",
							"Netherlands",
							"Netherlands Antilles",
							"New Caledonia",
							"New Zealand",
							"Nicaragua",
							"Niger",
							"Nigeria",
							"Niue",
							"Norfolk Island",
							"North Korea",
							"Northern Mariana Islands",
							"Norway",
							"Oman",
							"Pakistan",
							"Palau",
							"Palestine",
							"Panama",
							"Papua New Guinea",
							"Paraguay",
							"Peru",
							"Philippines",
							"Pitcairn",
							"Poland",
							"Portugal",
							"Puerto Rico",
							"Qatar",
							"Republic of Kosovo",
							"Reunion",
							"Romania",
							"Russia",
							"Rwanda",
							"Saint Kitts and Nevis",
							"Saint Lucia",
							"Saint Vincent and the Grenadines",
							"Samoa (Independent)",
							"San Marino",
							"Sao Tome and Principe",
							"Saudi Arabia",
							"Senegal",
							"Serbia",
							"Seychelles",
							"Sierra Leone",
							"Singapore",
							"Sint Maarten",
							"Slovakia",
							"Slovenia",
							"Solomon Islands",
							"Somalia",
							"South Africa",
							"South Georgia and the South Sandwich Islands",
							"South Korea",
							"South Sudan",
							"Spain",
							"Sri Lanka",
							"St. Helena",
							"St. Pierre and Miquelon",
							"Sudan",
							"Suriname",
							"Svalbard and Jan Mayen Islands",
							"Swaziland",
							"Sweden",
							"Switzerland",
							"Syria",
							"Taiwan",
							"Tajikistan",
							"Tanzania",
							"Thailand",
							"Togo",
							"Tokelau",
							"Tonga",
							"Trinidad and Tobago",
							"Tunisia",
							"Turkey",
							"Turkmenistan",
							"Turks & Caicos Islands",
							"Turks and Caicos Islands",
							"Tuvalu",
							"Uganda",
							"Ukraine",
							"United Arab Emirates",
							"United Kingdom",
							"United States of America",
							"Uruguay",
							"USA Minor Outlying Islands",
							"Uzbekistan",
							"Vanuatu",
							"Vatican City State (Holy See)",
							"Venezuela",
							"Vietnam",
							"Virgin Islands (British)",
							"Virgin Islands (U.S.)",
							"Wallis and Futuna Islands",
							"Western Sahara",
							"Yemen",
							"Zaire",
							"Zambia",
							"Zimbabwe"
						],
						"fb_name" : "country",
						"field_type" : "dropdown",
						"isGrouping" : false,
						"name" : "Nacionalidad / Nationality",
						"req" : true,
						"tag" : "COUNTRY"
					},
					
					{
						"choices" : 
						[
							":: Pais en el que vives? / Where do you live? ::",
							"Afghanistan",
							"Albania",
							"Algeria",
							"American Samoa",
							"Andorra",
							"Angola",
							"Anguilla",
							"Antarctica",
							"Antigua And Barbuda",
							"Argentina",
							"Armenia",
							"Aruba",
							"Australia",
							"Austria",
							"Azerbaijan",
							"Bahamas",
							"Bahrain",
							"Bangladesh",
							"Barbados",
							"Belarus",
							"Belgium",
							"Belize",
							"Benin",
							"Bermuda",
							"Bhutan",
							"Bolivia",
							"Bosnia and Herzegovina",
							"Botswana",
							"Bouvet Island",
							"Brazil",
							"British Indian Ocean Territory",
							"Brunei Darussalam",
							"Bulgaria",
							"Burkina Faso",
							"Burundi",
							"Cambodia",
							"Cameroon",
							"Canada",
							"Cape Verde",
							"Cayman Islands",
							"Central African Republic",
							"Chad",
							"Chile",
							"China",
							"Christmas Island",
							"Cocos (Keeling) Islands",
							"Colombia",
							"Comoros",
							"Congo",
							"Cook Islands",
							"Costa Rica",
							"Cote D'Ivoire",
							"Croatia",
							"Cuba",
							"Curacao",
							"Cyprus",
							"Czech Republic",
							"Denmark",
							"Djibouti",
							"Dominica",
							"Dominican Republic",
							"East Timor",
							"Ecuador",
							"Egypt",
							"El Salvador",
							"Equatorial Guinea",
							"Eritrea",
							"Estonia",
							"Ethiopia",
							"Falkland Islands",
							"Faroe Islands",
							"Fiji",
							"Finland",
							"France",
							"French Guiana",
							"French Polynesia",
							"French Southern Territories",
							"Gabon",
							"Gambia",
							"Georgia",
							"Germany",
							"Ghana",
							"Gibraltar",
							"Greece",
							"Greenland",
							"Grenada",
							"Guadeloupe",
							"Guam",
							"Guatemala",
							"Guernsey",
							"Guinea",
							"Guinea-Bissau",
							"Guyana",
							"Haiti",
							"Heard and Mc Donald Islands",
							"Honduras",
							"Hong Kong",
							"Hungary",
							"Iceland",
							"India",
							"Indonesia",
							"Iran",
							"Iraq",
							"Ireland",
							"Israel",
							"Italy",
							"Jamaica",
							"Japan",
							"Jersey  (Channel Islands)",
							"Jordan",
							"Kazakhstan",
							"Kenya",
							"Kiribati",
							"Kuwait",
							"Kyrgyzstan",
							"Lao People's Democratic Republic",
							"Latvia",
							"Lebanon",
							"Lesotho",
							"Liberia",
							"Libya",
							"Liechtenstein",
							"Lithuania",
							"Luxembourg",
							"Macau",
							"Macedonia",
							"Madagascar",
							"Malawi",
							"Malaysia",
							"Maldives",
							"Mali",
							"Malta",
							"Marshall Islands",
							"Martinique",
							"Mauritania",
							"Mauritius",
							"Mayotte",
							"Mexico",
							"Micronesia, Federated States of",
							"Moldova, Republic of",
							"Monaco",
							"Mongolia",
							"Montenegro",
							"Montserrat",
							"Morocco",
							"Mozambique",
							"Myanmar",
							"Namibia",
							"Nauru",
							"Nepal",
							"Netherlands",
							"Netherlands Antilles",
							"New Caledonia",
							"New Zealand",
							"Nicaragua",
							"Niger",
							"Nigeria",
							"Niue",
							"Norfolk Island",
							"North Korea",
							"Northern Mariana Islands",
							"Norway",
							"Oman",
							"Pakistan",
							"Palau",
							"Palestine",
							"Panama",
							"Papua New Guinea",
							"Paraguay",
							"Peru",
							"Philippines",
							"Pitcairn",
							"Poland",
							"Portugal",
							"Puerto Rico",
							"Qatar",
							"Republic of Kosovo",
							"Reunion",
							"Romania",
							"Russia",
							"Rwanda",
							"Saint Kitts and Nevis",
							"Saint Lucia",
							"Saint Vincent and the Grenadines",
							"Samoa (Independent)",
							"San Marino",
							"Sao Tome and Principe",
							"Saudi Arabia",
							"Senegal",
							"Serbia",
							"Seychelles",
							"Sierra Leone",
							"Singapore",
							"Sint Maarten",
							"Slovakia",
							"Slovenia",
							"Solomon Islands",
							"Somalia",
							"South Africa",
							"South Georgia and the South Sandwich Islands",
							"South Korea",
							"South Sudan",
							"Spain",
							"Sri Lanka",
							"St. Helena",
							"St. Pierre and Miquelon",
							"Sudan",
							"Suriname",
							"Svalbard and Jan Mayen Islands",
							"Swaziland",
							"Sweden",
							"Switzerland",
							"Syria",
							"Taiwan",
							"Tajikistan",
							"Tanzania",
							"Thailand",
							"Togo",
							"Tokelau",
							"Tonga",
							"Trinidad and Tobago",
							"Tunisia",
							"Turkey",
							"Turkmenistan",
							"Turks & Caicos Islands",
							"Turks and Caicos Islands",
							"Tuvalu",
							"Uganda",
							"Ukraine",
							"United Arab Emirates",
							"United Kingdom",
							"United States of America",
							"Uruguay",
							"USA Minor Outlying Islands",
							"Uzbekistan",
							"Vanuatu",
							"Vatican City State (Holy See)",
							"Venezuela",
							"Vietnam",
							"Virgin Islands (British)",
							"Virgin Islands (U.S.)",
							"Wallis and Futuna Islands",
							"Western Sahara",
							"Yemen",
							"Zaire",
							"Zambia",
							"Zimbabwe"
						],
						"fb_name" : "residency",
						"field_type" : "dropdown",
						"isGrouping" : false,
						"name" : "Lugar de Residencia / Place of Residence",
						"req" : true,
						"tag" : "RESIDENCY"
					},
					
					{
						"dateformat" : "",
						"fb_name" : "visaexpdat",
						"field_type" : "date",
						"isGrouping" : false,
						"name" : "Cuando vence tu visa? / When does your visa expire",
						"req" : false,
						"tag" : "VISAEXPDAT"
					},
					
					{
						"fb_name" : "visatype",
						"field_type" : "text",
						"isGrouping" : false,
						"name" : "Tipo de Visa / Visa Type",
						"req" : false,
						"tag" : "VISATYPE"
					},
					
					{
						"fb_name" : "phone",
						"field_type" : "phone",
						"isGrouping" : false,
						"name" : "Teléfono / Phone",
						"req" : false,
						"tag" : "PHONE"
					}
				],
				"name" : "VETA - VIVA, ESTUDIE Y TRABAJE EN AUSTRALIA",
				"subscribe" : 
				{
					"double_optin" : false,
					"email_address_field" : "EMAIL",
					"email_type_field" : "html",
					"replace_interests" : true,
					"send_welcome" : false,
					"update_existing" : true
				},
				"unsubscribe" : 
				{
					"delete_member" : false,
					"email_address_field" : "EMAIL",
					"send_goodbye" : true,
					"send_notify" : true
				}
			}
		]
	},
	"payment_settings" : 
	{
		"confirmpayment" : "<center>\n<style type=\"text/css\">\n#docContainer table {width:80%; margin-top: 5px; margin-bottom: 5px;}\n#docContainer td {text-align:right; min-width:25%; font-size: 12px !important; line-height: 20px;margin: 0px;border-bottom: 1px solid #e9e9e9; padding-right:5px;}\n#docContainer td:first-child {text-align:left; font-size: 13px !important; font-weight:bold; vertical-align:text-top; min-width:50%;}\n#docContainer th {font-size: 13px !important; font-weight:bold; vertical-align:text-top; text-align:right; padding-right:5px;}\n#docContainer th:first-child {text-align:left;}\n#docContainer tr:first-child {border-bottom-width:2px; border-bottom-style:solid;}\n#docContainer center {margin-bottom:15px;}\n#docContainer form input { margin:5px; }\n#docContainer #fb_confirm_inline { margin:5px; text-align:center;}\n#docContainer #fb_confirm_inline>center h2 { }\n#docContainer #fb_confirm_inline>center p { margin:5px; }\n#docContainer #fb_confirm_inline>center a { }\n#docContainer #fb_confirm_inline input { border:none; color:transparent; font-size:0px; background-color: transparent; background-repat: no-repeat; }\n#docContainer #fb_paypalwps { background: url('https://coffeecupimages.s3.amazonaws.com/paypal.gif');background-repeat:no-repeat; width:145px; height:42px; }\n#docContainer #fb_googlepay { background: url('https://coffeecupimages.s3.amazonaws.com/googlecheckout.gif'); background-repeat:no-repeat; width:168px; height:44px; }\n#docContainer #fb_authnet { background: url('https://coffeecupimages.s3.amazonaws.com/authnet.gif'); background-repeat:no-repeat; width:135px; height:38px; }\n#docContainer #fb_2checkout { background: url('https://coffeecupimages.s3.amazonaws.com/2co.png'); background-repeat:no-repeat; width:210px; height:44px; }\n#docContainer #fb_invoice { background: url('https://coffeecupimages.s3.amazonaws.com/btn_email.png'); background-repeat:no-repeat; width:102px; height:31px; }\n#docContainer #fb_invoice:hover { background: url('https://coffeecupimages.s3.amazonaws.com/btn_email_hov.png'); }\n#docContainer #fb_goback { color: inherit; }\n</style>\n[_cart_summary_]\n<h2>Almost done! </h2>\n<p>Your order will not be processed until you click the payment button below.</p>\n<a id=\"fb_goback\"href=\"?action=back\">Back to form</a></center>",
		"currencysymbol" : "$",
		"decimals" : 2,
		"fixedprice" : "000",
		"invoicelabel" : "",
		"is_present" : false,
		"paymenttype" : "redirect",
		"shopcurrency" : "USD",
		"usecustomsymbol" : false
	},
	"redirect_settings" : 
	{
		"confirmpage" : "<!DOCTYPE html>\n<html dir=\"ltr\" lang=\"en\">\n<head>\n<title>Success!</title>\n<meta charset=\"utf-8\">\n<style type=\"text/css\">\nbody {background: #f9f9f9;padding-left: 11%;padding-top: 7%; padding-right: 2%;max-width:700px;font-family: Helvetica, Arial;}\ntable{width:80%;}\np{font-size: 16px;font-weight: bold;color: #666;}\nh1{font-size: 60px !important;color: #ccc !important;margin:0px;}\nh2{font-size: 28px !important;color: #666 !important;margin: 0px; border-bottom: 1px dotted #00A2FF; padding-bottom:3px;}\nh3{font-size: 16px; color: #a1a1a1; border-top: 1px dotted #00A2FF; padding-top:1.7%; font-weight: bold;}\nh3 span{color: #ccc;}\ntd {font-size: 12px !important; line-height: 30px;  color: #666 !important; margin: 0px;border-bottom: 1px solid #e9e9e9;}\ntd:first-child {font-size: 13px !important; font-weight:bold; color: #333 !important; vertical-align:text-top; min-width:50%; padding-right:5px;}\na:link {color:#666; text-decoration:none;} a:visited {color:#666; text-decoration:none;} a:hover {color:#00A2FF;}\n</style>\n</head>\n<body>\n<h1>Thanks! </h1>\n<h2>The form is on its way.</h2>\n<p>Here&rsquo;s what was sent:</p>\n<div>[_form_results_]</div>\n<!-- link back to your Home Page -->\n<h3>Let&rsquo;s go <span> <a target=\"_blank\" href=\"http://www.coffeecup.com\">Back Home</a></span></h3>\n</body>\n</html>\n",
		"gotopage" : "http://www.australiaveta.com.au/registration-thank-you.html",
		"inline" : "<center>\n<style type=\"text/css\">\n#docContainer table {margin-top: 30px; margin-bottom: 30px; width:80%;}\n#docContainer td {font-size: 12px !important; line-height: 30px;color: #666666 !important; margin: 0px;border-bottom: 1px solid #e9e9e9;}\n#docContainer td:first-child {font-size: 13px !important; font-weight:bold; color: #333 !important; vertical-align:text-top; min-width:50%; padding-right:5px;}\n</style>\n[_form_results_]\n<h2>Thank you!</h2><br/>\n<p>Your form was successfully submitted. We received the information shown above.</p>\n</center>",
		"type" : "gotopage"
	},
	"uid" : "62f3522588d4256b7f460cb04658aeab",
	"validation_report" : "in_line"
},
"rules":{"fname":{"label":"Nombre / Name","fieldtype":"text","required":true},"lname":{"label":"Apellido / Last Name","fieldtype":"text","required":true},"email":{"email":true,"label":"Correo Electrónico / Email Address","fieldtype":"email","required":true},"dob":{"date":true,"label":"Fecha de Nacimiento / DOB","fieldtype":"date","date_config":{"minDate":null,"maxDate":null,"dateFormat":"US_SLASHED"},"required":true},"country":{"label":"Nacionalidad / Nationality","fieldtype":"dropdown","required":true,"values":["","Afghanistan","Albania","Algeria","American Samoa","Andorra","Angola","Anguilla","Antarctica","Antigua And Barbuda","Argentina","Armenia","Aruba","Australia","Austria","Azerbaijan","Bahamas","Bahrain","Bangladesh","Barbados","Belarus","Belgium","Belize","Benin","Bermuda","Bhutan","Bolivia","Bosnia and Herzegovina","Botswana","Bouvet Island","Brazil","British Indian Ocean Territory","Brunei Darussalam","Bulgaria","Burkina Faso","Burundi","Cambodia","Cameroon","Canada","Cape Verde","Cayman Islands","Central African Republic","Chad","Chile","China","Christmas Island","Cocos (Keeling) Islands","Colombia","Comoros","Congo","Cook Islands","Costa Rica","Cote D'Ivoire","Croatia","Cuba","Curacao","Cyprus","Czech Republic","Denmark","Djibouti","Dominica","Dominican Republic","East Timor","Ecuador","Egypt","El Salvador","Equatorial Guinea","Eritrea","Estonia","Ethiopia","Falkland Islands","Faroe Islands","Fiji","Finland","France","French Guiana","French Polynesia","French Southern Territories","Gabon","Gambia","Georgia","Germany","Ghana","Gibraltar","Greece","Greenland","Grenada","Guadeloupe","Guam","Guatemala","Guernsey","Guinea","Guinea-Bissau","Guyana","Haiti","Heard and Mc Donald Islands","Honduras","Hong Kong","Hungary","Iceland","India","Indonesia","Iran","Iraq","Ireland","Israel","Italy","Jamaica","Japan","Jersey  (Channel Islands)","Jordan","Kazakhstan","Kenya","Kiribati","Kuwait","Kyrgyzstan","Lao People's Democratic Republic","Latvia","Lebanon","Lesotho","Liberia","Libya","Liechtenstein","Lithuania","Luxembourg","Macau","Macedonia","Madagascar","Malawi","Malaysia","Maldives","Mali","Malta","Marshall Islands","Martinique","Mauritania","Mauritius","Mayotte","Mexico","Micronesia, Federated States of","Moldova, Republic of","Monaco","Mongolia","Montenegro","Montserrat","Morocco","Mozambique","Myanmar","Namibia","Nauru","Nepal","Netherlands","Netherlands Antilles","New Caledonia","New Zealand","Nicaragua","Niger","Nigeria","Niue","Norfolk Island","North Korea","Northern Mariana Islands","Norway","Oman","Pakistan","Palau","Palestine","Panama","Papua New Guinea","Paraguay","Peru","Philippines","Pitcairn","Poland","Portugal","Puerto Rico","Qatar","Republic of Kosovo","Reunion","Romania","Russia","Rwanda","Saint Kitts and Nevis","Saint Lucia","Saint Vincent and the Grenadines","Samoa (Independent)","San Marino","Sao Tome and Principe","Saudi Arabia","Senegal","Serbia","Seychelles","Sierra Leone","Singapore","Sint Maarten","Slovakia","Slovenia","Solomon Islands","Somalia","South Africa","South Georgia and the South Sandwich Islands","South Korea","South Sudan","Spain","Sri Lanka","St. Helena","St. Pierre and Miquelon","Sudan","Suriname","Svalbard and Jan Mayen Islands","Swaziland","Sweden","Switzerland","Syria","Taiwan","Tajikistan","Tanzania","Thailand","Togo","Tokelau","Tonga","Trinidad and Tobago","Tunisia","Turkey","Turkmenistan","Turks & Caicos Islands","Turks and Caicos Islands","Tuvalu","Uganda","Ukraine","United Arab Emirates","United Kingdom","United States of America","Uruguay","USA Minor Outlying Islands","Uzbekistan","Vanuatu","Vatican City State (Holy See)","Venezuela","Vietnam","Virgin Islands (British)","Virgin Islands (U.S.)","Wallis and Futuna Islands","Western Sahara","Yemen","Zaire","Zambia","Zimbabwe"]},"residency":{"label":"Lugar de Residencia / Place of Residence","fieldtype":"dropdown","required":true,"values":["","Afghanistan","Albania","Algeria","American Samoa","Andorra","Angola","Anguilla","Antarctica","Antigua And Barbuda","Argentina","Armenia","Aruba","Australia","Austria","Azerbaijan","Bahamas","Bahrain","Bangladesh","Barbados","Belarus","Belgium","Belize","Benin","Bermuda","Bhutan","Bolivia","Bosnia and Herzegovina","Botswana","Bouvet Island","Brazil","British Indian Ocean Territory","Brunei Darussalam","Bulgaria","Burkina Faso","Burundi","Cambodia","Cameroon","Canada","Cape Verde","Cayman Islands","Central African Republic","Chad","Chile","China","Christmas Island","Cocos (Keeling) Islands","Colombia","Comoros","Congo","Cook Islands","Costa Rica","Cote D'Ivoire","Croatia","Cuba","Curacao","Cyprus","Czech Republic","Denmark","Djibouti","Dominica","Dominican Republic","East Timor","Ecuador","Egypt","El Salvador","Equatorial Guinea","Eritrea","Estonia","Ethiopia","Falkland Islands","Faroe Islands","Fiji","Finland","France","French Guiana","French Polynesia","French Southern Territories","Gabon","Gambia","Georgia","Germany","Ghana","Gibraltar","Greece","Greenland","Grenada","Guadeloupe","Guam","Guatemala","Guernsey","Guinea","Guinea-Bissau","Guyana","Haiti","Heard and Mc Donald Islands","Honduras","Hong Kong","Hungary","Iceland","India","Indonesia","Iran","Iraq","Ireland","Israel","Italy","Jamaica","Japan","Jersey  (Channel Islands)","Jordan","Kazakhstan","Kenya","Kiribati","Kuwait","Kyrgyzstan","Lao People's Democratic Republic","Latvia","Lebanon","Lesotho","Liberia","Libya","Liechtenstein","Lithuania","Luxembourg","Macau","Macedonia","Madagascar","Malawi","Malaysia","Maldives","Mali","Malta","Marshall Islands","Martinique","Mauritania","Mauritius","Mayotte","Mexico","Micronesia, Federated States of","Moldova, Republic of","Monaco","Mongolia","Montenegro","Montserrat","Morocco","Mozambique","Myanmar","Namibia","Nauru","Nepal","Netherlands","Netherlands Antilles","New Caledonia","New Zealand","Nicaragua","Niger","Nigeria","Niue","Norfolk Island","North Korea","Northern Mariana Islands","Norway","Oman","Pakistan","Palau","Palestine","Panama","Papua New Guinea","Paraguay","Peru","Philippines","Pitcairn","Poland","Portugal","Puerto Rico","Qatar","Republic of Kosovo","Reunion","Romania","Russia","Rwanda","Saint Kitts and Nevis","Saint Lucia","Saint Vincent and the Grenadines","Samoa (Independent)","San Marino","Sao Tome and Principe","Saudi Arabia","Senegal","Serbia","Seychelles","Sierra Leone","Singapore","Sint Maarten","Slovakia","Slovenia","Solomon Islands","Somalia","South Africa","South Georgia and the South Sandwich Islands","South Korea","South Sudan","Spain","Sri Lanka","St. Helena","St. Pierre and Miquelon","Sudan","Suriname","Svalbard and Jan Mayen Islands","Swaziland","Sweden","Switzerland","Syria","Taiwan","Tajikistan","Tanzania","Thailand","Togo","Tokelau","Tonga","Trinidad and Tobago","Tunisia","Turkey","Turkmenistan","Turks & Caicos Islands","Turks and Caicos Islands","Tuvalu","Uganda","Ukraine","United Arab Emirates","United Kingdom","United States of America","Uruguay","USA Minor Outlying Islands","Uzbekistan","Vanuatu","Vatican City State (Holy See)","Venezuela","Vietnam","Virgin Islands (British)","Virgin Islands (U.S.)","Wallis and Futuna Islands","Western Sahara","Yemen","Zaire","Zambia","Zimbabwe"]},"visaexpdat":{"date":true,"label":"Cuando vence tu visa? / When does your visa expire","fieldtype":"date","date_config":{"minDate":null,"maxDate":null,"dateFormat":"US_SLASHED"}},"visatype":{"label":"Tipo de Visa / Visa Type","fieldtype":"text"},"phone":{"phone":"international","label":"Teléfono / Phone","fieldtype":"tel"},"recaptcha":{"captcha":"manual","public_key":"6Lfrk-ESAAAAAJbBvLAnSiPbVRLJz1spc7ZrZny1","private_key":"6Lfrk-ESAAAAAHbNUWSuROvm9JA3vll_ing_yYwr","fieldtype":"captcha"}},
"payment_rules":{"country":{},"residency":{}},
"conditional_rules":{"visaexpdat":{"element":{"name":"residency","operator":"is","value":"Australia"}},"visatype":{"element":{"name":"residency","operator":"is","value":"Australia"}}},
"application_version":"Web Form Builder (Windows), build 2.3.5217"
}